services:
  - type: web
    name: cardano-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate && python manage.py seed_menu && python manage.py init_admin && python manage.py init_info && gunicorn config.wsgi"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOW_ALL
        value: "1"
