# Generated by Django 5.1.15 on 2026-06-27 23:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Kennung')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Untertitel')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ['sort', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Artikelnummer')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Beschreibung')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preis (Euro, brutto)')),
                ('tax_rate', models.PositiveIntegerField(choices=[(10, '10 % (Speisen / Ayran)'), (20, '20 % (Getränke)')], default=10, verbose_name='Steuersatz')),
                ('image_url', models.URLField(blank=True, verbose_name='Bild-URL')),
                ('tags', models.CharField(blank=True, help_text='z. B. pop, veg, vegan, spicy', max_length=120, verbose_name='Tags (Komma)')),
                ('available', models.BooleanField(default=True, verbose_name='Verfuegbar')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.category', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Menue-Artikel',
                'verbose_name_plural': 'Menue-Artikel',
                'ordering': ['category__sort', 'sort', 'number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Bestellnummer')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eingegangen am')),
                ('status', models.CharField(choices=[('new', 'Neu'), ('confirmed', 'Bestaetigt'), ('preparing', 'In Zubereitung'), ('ready', 'Fertig'), ('delivering', 'In Lieferung'), ('done', 'Abgeschlossen'), ('cancelled', 'Storniert')], default='new', max_length=20, verbose_name='Status')),
                ('customer_name', models.CharField(max_length=160, verbose_name='Name')),
                ('phone', models.CharField(max_length=40, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('mode', models.CharField(choices=[('delivery', 'Lieferung'), ('pickup', 'Abholung')], default='delivery', max_length=10, verbose_name='Art')),
                ('street', models.CharField(blank=True, max_length=160, verbose_name='Strasse')),
                ('house_no', models.CharField(blank=True, max_length=20, verbose_name='Hausnr.')),
                ('stair', models.CharField(blank=True, max_length=20, verbose_name='Stiege')),
                ('door', models.CharField(blank=True, max_length=20, verbose_name='Tuer')),
                ('zip', models.CharField(blank=True, max_length=12, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Ort')),
                ('wish_time', models.CharField(blank=True, max_length=40, verbose_name='Wunschzeit')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Anmerkung')),
                ('payment', models.CharField(blank=True, max_length=40, verbose_name='Zahlung')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Zwischensumme')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Liefergebuehr')),
                ('tip', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Trinkgeld')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Gesamt')),
                ('vat_10', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='enth. MwSt. 10 %')),
                ('vat_20', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='enth. MwSt. 20 %')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Konto')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Artikel')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Einzelpreis')),
                ('tax_rate', models.PositiveIntegerField(default=10, verbose_name='Steuersatz')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
            ],
            options={
                'verbose_name': 'Bestellposition',
                'verbose_name_plural': 'Bestellpositionen',
            },
        ),
    ]
