# Generated by Django 5.1.15 on 2026-06-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cardano Kebapizza e.U.', max_length=120, verbose_name='Name')),
                ('owner', models.CharField(blank=True, max_length=120, verbose_name='Inhaber')),
                ('street', models.CharField(default='Etrichstraße 40/2/10A', max_length=160, verbose_name='Strasse')),
                ('zip', models.CharField(default='1110', max_length=12, verbose_name='PLZ')),
                ('city', models.CharField(default='Wien', max_length=80, verbose_name='Ort')),
                ('uid', models.CharField(default='ATU77114908', max_length=30, verbose_name='UID')),
                ('fn', models.CharField(default='FN 610587y', max_length=30, verbose_name='Firmenbuch')),
                ('gisa', models.CharField(default='34005309', max_length=30, verbose_name='GISA')),
                ('phone', models.CharField(default='+43 1 9258149', max_length=40, verbose_name='Telefon (Anzeige)')),
                ('phone_tel', models.CharField(default='+4319258149', max_length=40, verbose_name='Telefon (Wahl-Link)')),
                ('email', models.EmailField(default='order@cardanokebapizza.at', max_length=254, verbose_name='E-Mail')),
                ('hours', models.CharField(default='Täglich 11:00 – 23:00', max_length=120, verbose_name='Oeffnungszeiten')),
                ('payment', models.CharField(default='Bar, Karte, Pluxee, Edenred', max_length=160, verbose_name='Zahlung')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=2.9, max_digits=6, verbose_name='Liefergebuehr (Euro)')),
                ('free_delivery_from', models.DecimalField(decimal_places=2, default=20.0, max_digits=6, verbose_name='Gratis Lieferung ab (Euro)')),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/cardanokebapizza/', verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, default='https://www.facebook.com/p/Cardano-Kebapizza-61552703820637/', verbose_name='Facebook')),
                ('tiktok', models.URLField(blank=True, default='https://www.tiktok.com/@cardano.kebapizza', verbose_name='TikTok')),
                ('whatsapp', models.URLField(blank=True, default='https://wa.me/4319258149', verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Restaurantdaten',
                'verbose_name_plural': 'Restaurantdaten',
            },
        ),
    ]
