# Generated by Django 5.1.15 on 2026-06-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_restaurantinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='online_payment',
            field=models.BooleanField(default=False, verbose_name='Online-Zahlung aktiv'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='payment_provider',
            field=models.CharField(blank=True, default='stripe', max_length=30, verbose_name='Anbieter'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Stripe Publishable Key'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Stripe Secret Key'),
        ),
    ]
